name: deep_learning
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=1.2.0
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.15.0
  - ipython=8.14.0
  - jedi=0.18.2
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=3.0.9
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=3.9.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - pip:
      - contourpy==1.1.0
      - cycler==0.11.0
      - fonttools==4.41.1
      - kiwisolver==1.4.4
      - matplotlib==3.7.2
      - numpy==1.25.1
      - pandas==2.0.3
      - pillow==10.0.0
      - pyparsing==3.0.9
      - pytz==2023.3
      - tzdata==2023.3
prefix: /home/gruncrow/anaconda3/envs/deep_learning
